### ISSUE TITLE
Library not found in pip

### ISSUE THREAD

**Issue by theatischbein** [omemo/python-omemo#18]
I'm trying to install python-omemo on debian wheezy via pip 

~~~~
root@localhost:~# pip install python-omemo 
Downloading/unpacking python-omemo
  Could not find any downloads that satisfy the requirement python-omemo
No distributions at all found for python-omemo
Storing complete log in /root/.pip/pip.log
~~~~

But I get an error 404 response. Do I need to reconfigure pip or is the library removed from pip ?

~~~~
root@localhost:~# cat .pip/pip.log 
------------------------------------------------------------
/usr/bin/pip run on Mon Jun 26 21:31:34 2017
Downloading/unpacking python-omemo

  Getting page http://pypi.python.org/simple/python-omemo
  Could not fetch URL http://pypi.python.org/simple/python-omemo: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/python-omemo when looking for download links for python-omemo
  Getting page http://pypi.python.org/simple/
  URLs to search for versions for python-omemo:
  * http://pypi.python.org/simple/python-omemo/
  Getting page http://pypi.python.org/simple/python-omemo/
  Could not fetch URL http://pypi.python.org/simple/python-omemo/: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/python-omemo/ when looking for download links for python-omemo
  Could not find any downloads that satisfy the requirement python-omemo

No distributions at all found for python-omemo

~~~~

The exception information is the same for pip-2.7 or pip-3.2

~~~~
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 157, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for python-omemo
~~~~

Where is the error ?

**Comment by lovetox** [comment]
who says its on pip?

EDIT: ah i see the readme, hm does pip delete stuff after some time maybe?

**Comment by theatischbein** [comment]
Unfortunately I have no idea how pip is working.

Did you have any experiences on installing python-omemo via tox with debian non-unstable sources ? I can't resolve the dependencies that tox is trying to install.

**Comment by lovetox** [comment]
did you try to clone the repo, cd into the dir and execute `python setup.py install` on the commandline

**Comment by theatischbein** [comment]
wow! okay that was simple. I was trying to compile it my self with tox.
The setup script worked perfectly thanks!
